"""
Django settings for jobboard project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta

import environ
import os

env = environ.Env()
environ.Env.read_env()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!8&gd8a=0$p6+(lbi-jzvzo4)!5^zjla0j!v1=_ypxy#)drjn9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #third party 
    'django_extensions',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'django_celery_beat',

    #local apps
    'accounts.apps.AccountsConfig',
    'jobs.apps.JobsConfig',
    'applications.apps.ApplicationsConfig',
    'notifications.apps.NotificationsConfig',
    'blog.apps.BlogConfig',
]

# settings.py — add this anywhere after INSTALLED_APPS
REST_FRAMEWORK = {
   
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # default permission — allow read, require auth for write
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],

    # default pagination — always paginate
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # default renderer — JSON only for API
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

SIMPLE_JWT = {
    # TTL for access tokens
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),

    # TTL for refresh token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # if True - each refresh call ratates the refresh token
    # olf refresh token is invalidated, new one issued
    # more secure - limits refresh token reuse
    'ROTATE_REFRESH_TOKENS': True,

    # if True - old refresh token are blacklisted after rotation
    # requires token_blacklist app in INSTALLED_APPS
    'BLACKLIST_AFTER_ROTATION': True,

    #  the header type - Authorization: Bearer <token>
    'AUTH_HEADER_TYPES': ('Bearer',),

    # what field from User model goes into token
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id'
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


    # custom middleware
    'jobboard.middleware.RequestLoggerMiddleware',
    'jobboard.middleware.MaintenanceModeMiddleware',
    'jobboard.middleware.RoleAuditMiddleware',
    'jobboard.middleware.JsonExceptionMiddleware',
]

ROOT_URLCONF = 'jobboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
       'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='jobboard_db'),
        'USER': env('DB_USER', default='postgres'),
        'PASSWORD': env('DB_PASSWORD', default='postgres'),
        'HOST': env('DB_HOST', default='localhost'),  # 'db' in Docker
        'PORT': env('DB_PORT', default='5432'),
    }
}

# Redis — single URL config
REDIS_URL = env('REDIS_URL', default='redis://127.0.0.1:6379/0')

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'


#sql query in terminal
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # middleware logger
        'jobboard.middleware': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # signals
        'accounts.signals': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'applications.signals': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'applications.tasks': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'jobs.signals': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django SQL query logger
        # 'django.db.backends': {
        #     'handlers': ['console'],
        #     'level': 'DEBUG',
        #     'propagate': False,
        # },
    },
}


MAINTENANCE_MODE = False

CACHES = {
     'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'JobBoard API',
    'DESCRIPTION': '''
        A production-ready job board REST API built with Django and DRF.
        
        Features
        - JWT authentication with role-based access (company / candidate / admin)
        - Job listing CRUD with advanced filtering and full-text search
        - Application tracking system
        - Redis caching for performance
        - Dockerized with PostgreSQL and Redis
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # group endpoints by app
    'SCHEMA_PATH_PREFIX': '/api/v1/',

    # show authentication button in Swagger UI
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,   # keeps token after page refresh
        'displayRequestDuration': True, # shows how long each request took
        'filter': True,                 # search box to filter endpoints
    },

    # security scheme — tells Swagger how to send the JWT token
    'SECURITY': [{'bearerAuth': []}],
}

REDIS_URL = env('REDIS_URL', default='redis://127.0.0.1:6379/0')

# Celery config
CELERY_BROKER_URL = env('REDIS_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://redis:6379/0')

# serialization
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# timezone - important for scheduled taks
CELERY_TIMEZONE = 'Asia/Tokyo'
CELERY_ENABLE_UTC = True

# task behaviour
CELERY_TASK_TRACK_STARTED = True      # task shows 'STARTED' state
CELERY_TASK_TIME_LIMIT = 30 * 60      # hard limit : 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60 # soft limit: 25 minutes (raises exception)

# retry behaviour
CELERY_TASKS_ACKS_LATE = True
# if worker crashes mid-task, task goes back to queue
# safer but means tasks must be idempotent

# result expiry - clean up old results after 24 hours
CELERY_RESULT_EXPIRES = 86400


#CELERY_WORKER_HIJACK_ROOT_LOGGER = False

from celery.schedules import crontab

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_BEAT_SCHEDULE = {

    # deactivate expire jobs - every night at midnight Tokyo time
    'deactivate-expired-jobs': {
        'task': 'jobs.tasks.deactivate_expired_jobs',
        'schedule': crontab(hour=0, minute=0), # 00.00 every day
    },

    # weekly job digest - every Sunday at 9am Tokyo time
    'weekly-job-digest': { 
        'task': 'jobs.tasks.send_weekly_job_digest',
        'schedule': crontab(
            hour=9,
            minute=0,
            day_of_week='sunday'
        ),
        },

    # remind compaies about unreviewed applications
    # every weekday at 8 am
    'remind-unreviewed-application': {
        'task': 'applications.tasks.remind_unreviewed_applications',
        'schedule': crontab(
            hour=8,
            minute=0,
            day_of_week='monday-friday',
        )
    },

    # clean up expired cache keys - every hour
    'cleanup-cache': {
        'task': 'jobs.tasks.cleanup_stale_cache',
        'schedule': crontab(minute=0) # top of every hour
    },


}


# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='sandbox.smtp.mailtrap.io')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@jobboard.com')